// <auto-generated />
namespace DoAn_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Update1303 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update1303));
        
        string IMigrationMetadata.Id
        {
            get { return "202303131446211_Update1303"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
